spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
<<<<<<< HEAD
    password:
=======
    password: ****
>>>>>>> b5f4e266da654ad48a084c0e94649e962bd7a502
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true

  sql:
    init:
      mode: never

